---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность восстановить пароль через email
  - Пользователь должен иметь возможность войти на сайт через почту и пароль
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Пользователь должен иметь возможность отправить запрос на игру любому игроку, другу или играть с ботом
  - Пользователь должен иметь возможность установить таймер для игры
  - Пользователь должен иметь возможность выбрать задание в игре
  - Пользователь не должен иметь возможность копировать код
  - Пользователь в своем профиле должен иметь возможность видеть свою статистику на платформе, а именно рейтинг, количество решенных задач
  - Пользователь должен иметь возможность написать в чате с другими зарегистрированными пользователями
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров: Google Chrome, Mozilla Firefox, Safari.
implicit:
  - Интерфейс сайта должен быть интуитивно понятным и простым в использовании.
  - Сайт должен быстро реагировать на действия пользователей.
