---
functional:
  - Пользователь должен иметь возможность восстановить пароль через email
  - Пользователь в своем профиле должен иметь возможность видеть свою статистику на платформе, а именно рейтинг, количество решенных задач
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Интерфейс сайта должен быть интуитивно понятным и простым в использовании.
  - Сайт должен быстро реагировать на действия пользователей.
